title: YSS's Study
author: Yeonsang Shin
email: samshin3910@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  틈틈이 공부하는 것들
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /category/:categories/:title/
texture:
  title: YSS's Study
  tagline: Developer. SSHS 28, SNU ECE 19
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  # If you want to open Comments, uncomment this
  # disqus_shortname: yxxshin-study

  # Making Navigation
  navigation:
    - title: Home
      url: "/"
    - title: Algorithm
      url: "/category/algorithm"
    - title: Baekjoon
      url: "/category/baekjoon"
    - title: Search
      url: "/search"


  # Category List
  category_list: [ Algorithm, Baekjoon ]

  # generate social links in footer
  social_links:
    twitter: null
    github:  yxxshin
    linkedIn: null
    rss: null
    instagram: yxxshin0209
    baekjoon: samshin3910
 
# Tipque Search
tipque_search:
  include:
    pages: false      # pages 레이아웃은 검색하지 않는다
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]   # 검색 항목에서 제외
    categories: []
    tags: []

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
